### ISSUE TITLE
Event Title

### ISSUE THREAD

**Issue by Iam-Ignite** [zurichat/zc_plugin_company_holiday_calendar#332]
Add a event title for users to know the main event

**Comment by Babatunde-Ben** [comment]
### Added "event title" input on the "add event" sidebar of the Holiday calendar plugin so that users can know the title of the event.
check live link here https://calendar.zuri.chat/
check figma link here https://www.figma.com/file/V9hWgfsAPJFU3izkO2yruc/Zuri-Holiday-Calendar-Plugin?node-id=0%3A1


![Event title issue](https://user-images.githubusercontent.com/68576237/132227892-3a8fb9cc-3d19-466a-bae1-f72166b0401d.png)
